// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5fWFTb5-rUJfKqoQ7WDB3FR3OV1zVsoI',
    appId: '1:453725556263:web:345963a4efda886173c802',
    messagingSenderId: '453725556263',
    projectId: 'cb-reborn',
    authDomain: 'cb-reborn.firebaseapp.com',
    storageBucket: 'cb-reborn.firebasestorage.app',
    measurementId: 'G-6Q5XTDL5VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgPmeq8RA3k3bqfmDVa-Rg99wsS59egxM',
    appId: '1:453725556263:android:62ca93d1c0d2214673c802',
    messagingSenderId: '453725556263',
    projectId: 'cb-reborn',
    storageBucket: 'cb-reborn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqVYGgmpj8BcEuw8D7lfmep-XbFcyt_Iw',
    appId: '1:453725556263:ios:c5218c9c78a85bae73c802',
    messagingSenderId: '453725556263',
    projectId: 'cb-reborn',
    storageBucket: 'cb-reborn.firebasestorage.app',
    iosBundleId: 'com.clubblackout.cbPlayer',
  );
}
